/*----------------------------------------------------------------------------------------SOLUCION---------------------------------------------------------------------------------*/
/*1*/
ALTER TABLE AUTORLIBRO
    DROP CONSTRAINT FK_AUTOR;

ALTER TABLE AUTOR
    DROP CONSTRAINT PK_AUTOR
    ADD CONSTRAINT PK_AUTOR PRIMARY KEY(NOMBRE,APELLIDOS)
    DROP COLUMN ID /*No necesario*/

ALTER TABLE AUTORLIBRO
    ADD COLUMN NOMBRE VARCHAR(100)
    ADD COLUMN APELLIDOS VARCHAR(100)
    DROP COLUMN ID
    ADD CONSTRAINT FK_AUTOR FOREIGN KEY (NOMBRE, APELLIDOS) REFERENCES AUTOR (NOMBRE,APELLIDOS)

/*2*/
INSERT INTO EJEMPLAR
    SELECT LIBRO, MAX(EJEMPLAR)+1, MIN(BIBLIOTECA),(CURRENT_DATE()-7), (CURRENT_DATE())
    FROM EJEMPLAR
    GROUP BY LIBRO;

/*3*/
SELECT A.NOMBRE,A.APELLIDOS,L.TITULO
FROM AUTOR AS A
	JOIN AUTORLIBRO AS AA ON AA.AUTOR=A.ID
	JOIN PRESTAMO AS P ON P.LIBRO=AA.LIBRO
    JOIN LIBRO AS L ON L.ID=AA.LIBRO
    GROUP BY AA.AUTOR,AA.LIBRO,A.NOMBRE,A.APELLIDOS,L.TITULO
	HAVING COUNT(DISTINCT P.EJEMPLAR)>=3;

/*4*/
SELECT B.ID,B.NOMBRE,
    FROM (BIBLIOTECA AS B
        JOIN EJEMPLAR AS E ON E.BIBLIOTECA=B.ID) 
        LEFT JOIN PRESTAMOS AS P ON E.LIBRO=P.LIBRO AND E.EJEMPLAR=P.EJEMPLAR
    GROUP BY B.ID, B.NOMBRE
    HAVING COUNT(DISTINCT E.LIBRO)-COUNT(DISTINCT P.LIBRO)<COUNT(DISTINCT P.LIBRO)
UNION ALL
SELECT B.ID, B.NOMBRE
FROM BIBLIOTECA AS B 
    JOIN LECTOR AS LC ON GET_LOCALIDAD(B.DIRECCION)=GET_LOCALIDAD(LC.DIRECCION)
    WHERE YEAR(LC.FECHA_INSCRIPCION)>1995
    GROUP BY B.ID, B.NOMBRE
    HAVING COUNT(*)>=5